#!/bin/dash

[ "$2" = "up" ] || [ "$2" = "down" ] && echo "wifi%{A:urxvt -sr -bl -e nmtui &:}%{U#00bcd4}%{+u}  %{F#FFFFFF}$(echo $(nmcli -t -f active,ssid,bars dev wifi | grep yes) | cut -d\: -f2) %{-u}%{A}" > "/tmp/lemon/panel_fifo"
