#!/bin/dash
#
# Based on ideas in a script found at
# http://icculus.org/pipermail/openbox/2013-January/007772.html
#
# Written  by damo <damo@bunsenlabs.org> October 2015
# Modified by jaft <jaft.r@outlook.com>  2019
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file LICENSE.  If not, see
# <https://www.gnu.org/licenses/>.
#
## Commentary:
#
# The script snaps a window to left or right halves of screen, or top and
# bottom, using X window properties for getting and storing values.
#
# Left, right, top, or bottom screen margins can be specified (negative values allowed);
# Works with dual monitors - windows will snap to edges of monitor they are on;
# Honours user-defined Openbox left and right screen margins;
# Works with decorated and undecorated windows, and windows with no borders;
# Doesn't cover panels at top,bottom, desktop left or desktop right.
#
# REQUIRES: xdotool, wmctrl
#
########################################################################
#
# TODO: Account for _NET_WORKAREA with top/bottom snapping if panel only
# appears on the other monitor.
#
########################################################################

getWindowProperty() {
	window_ID="$1"
	property_name="$2"

	echo $(xprop -id $window_ID $property_name | awk '{print $3}')
}

setPropertyInteger() {
	window_ID="$1"
	property_name="$2"
	property_value="$3"

	xprop -id  "$window_ID"                       \
	      -f   "$property_name" 32i               \
	      -set "$property_name" "$property_value"
}
setPropertyString() {
	window_ID="$1"
	property_name="$2"
	property_value="$3"

	xprop -id  "$window_ID"                       \
	      -f   "$property_name" 8s                \
	      -set "$property_name" "$property_value"
}

storeGeometry() {
	window_ID="$1"




	MON=$(xrandr -q | grep -c " connected")

	case $MON in
		1 | 2 )
			setPropertyInteger $window_ID "_MONITORS" "$MON"
			;;
		3 | * )
			echo "Script cannot deal with more than 2 monitors" >&2

			exit
			;;
	esac




	eval $(xdotool getactivewindow getwindowgeometry --shell)

	# Set initial geometry and position
	setPropertyInteger $window_ID "_INITIAL_DIMENSION_X"      "$X"
	setPropertyInteger $window_ID "_INITIAL_DIMENSION_Y"      "$Y"
	setPropertyInteger $window_ID "_INITIAL_DIMENSION_WIDTH"  "$WIDTH"
	setPropertyInteger $window_ID "_INITIAL_DIMENSION_HEIGHT" "$HEIGHT"




	# WM sets window frame and border sizes
	# Titlebar height depends on fontsize of Active titlebar
	win_EXTENTS=$(xprop -id $window_ID _NET_FRAME_EXTENTS | awk ' {gsub(/,/,"");print $3,$4,$5,$6}')
	read BORDER_L BORDER_R BORDER_T BORDER_B <<< "$win_EXTENTS"

	setPropertyInteger $window_ID "_OB_BORDER_L" "$BORDER_L"
	setPropertyInteger $window_ID "_OB_BORDER_R" "$BORDER_R"
	setPropertyInteger $window_ID "_OB_BORDER_T" "$BORDER_T"
	setPropertyInteger $window_ID "_OB_BORDER_B" "$BORDER_B"
	setPropertyInteger $window_ID "_OFFSET_X"    "$(($BORDER_L + $BORDER_R))"

	# Use different corrections if window is decorated/undecorated
	if
		xprop -id $window_ID | grep -q _OB_WM_STATE_UNDECORATED
	then
		setPropertyInteger $window_ID "_OFFSET_Y" "$(($BORDER_T + $BORDER_B))"
	else
		setPropertyInteger $window_ID "_OFFSET_Y" "$(($BORDER_T * 2))"
	fi




	RC="$HOME/.config/openbox/rc.xml"

	if
		[ -f "$RC" ]
	then
		TAG="margins"
		RCXML=$(sed -n "/<$TAG>/,/<\/$TAG>/p" "$RC")

		setPropertyInteger $window_ID "_OB_MARGIN_L" $(grep -oPm1 "(?<=<left>)[^<]+"   <<< "$RCXML")
		setPropertyInteger $window_ID "_OB_MARGIN_R" $(grep -oPm1 "(?<=<right>)[^<]+"  <<< "$RCXML")
		setPropertyInteger $window_ID "_OB_MARGIN_T" $(grep -oPm1 "(?<=<top>)[^<]+"    <<< "$RCXML")
		setPropertyInteger $window_ID "_OB_MARGIN_B" $(grep -oPm1 "(?<=<bottom>)[^<]+" <<< "$RCXML")
	else
		echo "$RC not found" >&2

		exit 1
	fi
}

restoreDimensionGeometry() {
	window_ID="$1"



	x_position=$(( $(getWindowProperty $window_ID "_INITIAL_DIMENSION_X") -
	               $(getWindowProperty $window_ID "_OFFSET_X")            ))
	y_position=$(( $(getWindowProperty $window_ID "_INITIAL_DIMENSION_Y") -
	               $(getWindowProperty $window_ID "_OFFSET_Y")            ))
	initial_width=$(getWindowProperty $window_ID "_INITIAL_DIMENSION_WIDTH")
	initial_height=$(getWindowProperty $window_ID "_INITIAL_DIMENSION_HEIGHT")

	wmctrl -r :ACTIVE: -b remove,maximized_vert &&                                         \
	wmctrl -r :ACTIVE: -b remove,maximized_horz &&                                         \
	wmctrl -r :ACTIVE: -e 0,"$x_position","$y_position","$initial_width","$initial_height"

	xprop -id $window_ID -remove _MONITORS
	xprop -id $window_ID -remove _STATE
	xprop -id $window_ID -remove _INITIAL_DIMENSION_X
	xprop -id $window_ID -remove _INITIAL_DIMENSION_Y
	xprop -id $window_ID -remove _INITIAL_DIMENSION_WIDTH
	xprop -id $window_ID -remove _INITIAL_DIMENSION_HEIGHT
	xprop -id $window_ID -remove _OFFSET_X
	xprop -id $window_ID -remove _OFFSET_Y
	xprop -id $window_ID -remove _OB_BORDER_L
	xprop -id $window_ID -remove _OB_BORDER_R
	xprop -id $window_ID -remove _OB_BORDER_T
	xprop -id $window_ID -remove _OB_BORDER_B
	xprop -id $window_ID -remove _OB_MARGIN_L
	xprop -id $window_ID -remove _OB_MARGIN_R
	xprop -id $window_ID -remove _OB_MARGIN_T
	xprop -id $window_ID -remove _OB_MARGIN_B
}

getScreenDimensions() {   # get net workarea, if panels are present
	window_ID="$1"
	number_of_monitors="$2"



	#    X pos, Y pos, usable width, usable height
	read valX   valY   valW          valH          <<< $(echo $(xprop -root _NET_WORKAREA) | awk '{gsub(/,/,"");print $3,$4,$5,$6}')

	desktopW=$(xrandr -q | awk '/Screen/ {print $8}')  # total desktop width

	# Get monitors geometry and position ( w,h,offset_x,offset_y )
	read monA     \
	     monAgeom \
	     monB     \
	     monBgeom <<< $(echo $(xrandr -q                                                             |
	                           awk '/ connected/ {if ($3=="primary") print $1,$4; else print $1,$3}'))

	monApos=$(echo $monAgeom | awk -F "+" '{print $2}') # get offset_x
	monBpos=$(echo $monBgeom | awk -F "+" '{print $2}')
	if
		[ $number_of_monitors != 1 ]        # test if there are 2 monitors
	then
		if
			[ $monApos -lt $monBpos ]
		then
			screenW1=${monAgeom%'x'*}   # width of left screen
			screenW2=${monBgeom%'x'*}   # width of right screen
		else
			screenW2=${monAgeom%'x'*}
			screenW1=${monBgeom%'x'*}
		fi
	else
		screenW1=${monAgeom%'x'*}       # only one screen
	fi

	WINPOS=$(xwininfo -id $WINDOW | grep "Absolute upper-left X")

	if
		[ ${WINPOS##*' '} -ge $screenW1 ]
	then # window is on R monitor
		X_zero=$(( $desktopW - $screenW2 ))
		screenW=$(( $desktopW - $screenW1 - $(( $desktopW - $valW - $valX )) ))
	else
		X_zero=$valX                            # window is on L monitor
		screenW=$(( $screenW1 - $X_zero ))
	fi
}

getXpositionForLeftSnap() {
	window_ID="$1"
	margin_passed_in="$2"
	x_coord_of_monitor="$3"



	OB_border_left=$(getWindowProperty $window_ID "_OB_BORDER_L")

	if
		[ $margin_passed_in -ne 0 ]
	then
		if
			[ $margin_passed_in -lt $OB_border_left ]
		then
			echo $((                     $OB_border_left + $x_coord_of_monitor ))
		else
			echo $(( $margin_passed_in + $OB_border_left + $x_coord_of_monitor ))
		fi
	else
		echo $(( $(getWindowProperty $window_ID "_OB_MARGIN_L") + $x_coord_of_monitor ))
	fi
}

getWindowWidthForRightSnap() {
	window_ID="$1"
	margin_passed_in_by_user="$2"
	monitor_width="$3"



	OB_border_right=$(getWindowProperty $window_ID "_OB_BORDER_R")

	if
		[ $margin_passed_in_by_user -ne 0 ]
	then
		if
			[ $margin_passed_in_by_user -le $OB_border_right ]
		then
			margin_right="$OB_border_right"     # don't need OB margin
		else
			margin_right=$(( $margin_passed_in_by_user + $OB_border_right ))
		fi
	else
		margin_right="$OB_border_right"       # add OB margin to right edge
	fi

	echo $(( ($monitor_width / 2)                        -
	         $margin_right                               -
	         $(getWindowProperty $window_ID "_OFFSET_X") ))
}
####    END FUNCTIONS   ################################################



if
	[ $2 ]
then
	MARGIN=$2
else
	MARGIN=0
fi

WINDOW=$(xdotool getactivewindow)



case "$1" in
	-l|--left)
		case $(getWindowProperty $WINDOW "_STATE") in
			"such" | "found.")
				storeGeometry $WINDOW

				# Provides $X_zero and $screenW
				getScreenDimensions $window_ID $(getWindowProperty $window_ID "_MONITORS")

				x_position=$(getXpositionForLeftSnap $WINDOW $MARGIN $X_zero)
				WIN_WIDTH_L=$(( ($screenW / 2)                           -
				                $x_position                              -
				                $(getWindowProperty $WINDOW "_OFFSET_X") +
				                $X_zero                                  ))

				# If we've gotten this far without the program quitting, we can set this
				setPropertyString $WINDOW "_STATE" JUST_LEFT

				# Move window
				wmctrl -r :ACTIVE: -b    add,maximized_vert             && \
				wmctrl -r :ACTIVE: -b remove,maximized_horz             && \
				wmctrl -r :ACTIVE: -e 0,$x_position,0,"$WIN_WIDTH_L",-1
				;;
			"\"JUST_RIGHT\"")
			  restoreDimensionGeometry $WINDOW
				;;
			"\"TOP_RIGHT\"")
				setPropertyString $WINDOW "_STATE" JUST_TOP
				;;&
			"\"BOT_RIGHT\"")
				setPropertyString $WINDOW "_STATE" JUST_BOTTOM
				;;&
			"\"TOP_RIGHT\"" | "\"BOT_RIGHT\"")
				wmctrl -r :ACTIVE: -b add,maximized_horz
				;;
			"\"JUST_TOP\"" | "\"JUST_BOTTOM\"")
				# Provides $X_zero and $screenW
				getScreenDimensions $window_ID $(getWindowProperty $window_ID "_MONITORS")

				x_position=$(getXpositionForLeftSnap $WINDOW $MARGIN $X_zero)
				WIN_WIDTH_L=$(( ($screenW / 2)                           -
				                $x_position                              -
				                $(getWindowProperty $WINDOW "_OFFSET_X") +
				                $X_zero                                  ))

				# Move window
				wmctrl -r :ACTIVE: -b remove,maximized_horz                && \
				wmctrl -r :ACTIVE: -e 0,"$x_position",-1,"$WIN_WIDTH_L",-1
				;;&
			"\"JUST_TOP\"")
				setPropertyString $WINDOW "_STATE" TOP_LEFT
				;;&
			"\"JUST_BOTTOM\"")
				setPropertyString $WINDOW "_STATE" BOT_LEFT
				;;
			"\"MAXIMIZED\"")
				# Provides $X_zero and $screenW
				getScreenDimensions $window_ID $(getWindowProperty $window_ID "_MONITORS")

				x_position=$(getXpositionForLeftSnap $WINDOW $MARGIN $X_zero)
				WIN_WIDTH_L=$(( ($screenW / 2)                           -
				                $x_position                              -
				                $(getWindowProperty $WINDOW "_OFFSET_X") +
				                $X_zero                                  ))

				# If we've gotten this far without the program quitting, we can set this
				setPropertyString $WINDOW "_STATE" JUST_LEFT

				# Move window
				wmctrl -r :ACTIVE: -b    add,maximized_vert             && \
				wmctrl -r :ACTIVE: -b remove,maximized_horz             && \
				wmctrl -r :ACTIVE: -e 0,$x_position,0,"$WIN_WIDTH_L",-1
				;;
			*)
				exit
				;;
		esac
		;;
	-r|--right)
		case $(getWindowProperty $WINDOW "_STATE") in
			"such" | "found.")
				storeGeometry $WINDOW

				# Provides $X_zero and $screenW
				getScreenDimensions $WINDOW $(getWindowProperty $WINDOW "_MONITORS")

				x_position=$(( ($screenW / 2) + $X_zero ))
				window_width=$(getWindowWidthForRightSnap $WINDOW $MARGIN $screenW)

				# If we've gotten this far without the program quitting, we can set this
				setPropertyString $WINDOW "_STATE" JUST_RIGHT

				# Move window
				wmctrl -r :ACTIVE: -b    add,maximized_vert                && \
				wmctrl -r :ACTIVE: -b remove,maximized_horz                && \
				wmctrl -r :ACTIVE: -e 0,"$x_position",0,"$window_width",-1
				;;
			"\"JUST_LEFT\"")
				restoreDimensionGeometry $WINDOW
				;;
			"\"TOP_LEFT\"")
				setPropertyString $WINDOW "_STATE" JUST_TOP
				;;&
			"\"BOT_LEFT\"")
				setPropertyString $WINDOW "_STATE" JUST_BOTTOM
				;;&
			"\"TOP_LEFT\"" | "\"BOT_LEFT\"")
				wmctrl -r :ACTIVE: -b add,maximized_horz
				;;
			"\"JUST_TOP\"" | "\"JUST_BOTTOM\"")
				# Provides $X_zero and $screenW
				getScreenDimensions $WINDOW $(getWindowProperty $WINDOW "_MONITORS")

				x_position=$(( ($screenW / 2) + $X_zero ))
				window_width=$(getWindowWidthForRightSnap $WINDOW $MARGIN $screenW)

				# Move window
				wmctrl -r :ACTIVE: -b remove,maximized_horz                 && \
				wmctrl -r :ACTIVE: -e 0,"$x_position",-1,"$window_width",-1
				;;&
			"\"JUST_TOP\"")
				setPropertyString $WINDOW "_STATE" TOP_RIGHT
				;;&
			"\"JUST_BOTTOM\"")
				setPropertyString $WINDOW "_STATE" BOT_RIGHT
				;;
			"\"MAXIMIZED\"")
				# Provides $X_zero and $screenW
				getScreenDimensions $WINDOW $(getWindowProperty $WINDOW "_MONITORS")

				x_position=$(( ($screenW / 2) + $X_zero ))
				window_width=$(getWindowWidthForRightSnap $WINDOW $MARGIN $screenW)

				# If we've gotten this far without the program quitting, we can set this
				setPropertyString $WINDOW "_STATE" JUST_RIGHT

				# Move window
				wmctrl -r :ACTIVE: -b    add,maximized_vert                && \
				wmctrl -r :ACTIVE: -b remove,maximized_horz                && \
				wmctrl -r :ACTIVE: -e 0,"$x_position",0,"$window_width",-1
				;;
			*)
				exit
				;;
		esac
		;;
	-u|--up)
		case $(getWindowProperty $WINDOW "_STATE") in
			"such" | "found.")
				storeGeometry $WINDOW

				# Provides $valY and $valH
				getScreenDimensions $WINDOW $(getWindowProperty $WINDOW "_MONITORS")

				margin_top=$(( $MARGIN + $(getWindowProperty $WINDOW "_OB_MARGIN_T") ))
				y_position=$(( $valY + $margin_top ))
				window_height_top=$(( ($valH/2)                                   -
				                      $(getWindowProperty $WINDOW "_OB_BORDER_T") -
				                      $(getWindowProperty $WINDOW "_OB_BORDER_B") -
				                      $margin_top                                 ))

				# If we've gotten this far without the program quitting, we can set this
				setPropertyString $WINDOW "_STATE" JUST_TOP

				# Move window
				wmctrl -r :ACTIVE: -b remove,maximized_vert                      && \
				wmctrl -r :ACTIVE: -b    add,maximized_horz                      && \
				wmctrl -r :ACTIVE: -e 0,-1,"$y_position",-1,"$window_height_top"
				;;
			"\"JUST_LEFT\"" | "\"JUST_RIGHT\"")
				# Provides $valY and $valH
				getScreenDimensions $WINDOW $(getWindowProperty $WINDOW "_MONITORS")

				margin_top=$(( $MARGIN + $(getWindowProperty $WINDOW "_OB_MARGIN_T") ))
				y_position=$(( $valY + $margin_top ))
				window_height_top=$(( ($valH/2)                                   -
				                      $(getWindowProperty $WINDOW "_OB_BORDER_T") -
				                      $(getWindowProperty $WINDOW "_OB_BORDER_B") -
				                      $margin_top                                 ))

				# Move window
				wmctrl -r :ACTIVE: -b remove,maximized_vert                      && \
				wmctrl -r :ACTIVE: -e 0,-1,"$y_position",-1,"$window_height_top"
				;;&
			"\"JUST_LEFT\"")
				setPropertyString $WINDOW "_STATE" TOP_LEFT
				;;&
			"\"JUST_RIGHT\"")
				setPropertyString $WINDOW "_STATE" TOP_RIGHT
				;;
			"\"BOT_LEFT\"")
				setPropertyString $WINDOW "_STATE" JUST_LEFT
				;;&
			"\"BOT_RIGHT\"")
				setPropertyString $WINDOW "_STATE" JUST_RIGHT
				;;&
			"\"BOT_LEFT\"" | "\"BOT_RIGHT\"")
				wmctrl -r :ACTIVE: -b add,maximized_vert
				;;
			"\"JUST_TOP\"")
				setPropertyString $WINDOW "_STATE" MAXIMIZED

				wmctrl -r :ACTIVE: -b add,maximized_vert && \
				wmctrl -r :ACTIVE: -b add,maximized_horz
				;;
			"\"JUST_BOTTOM\"")
				restoreDimensionGeometry $WINDOW
				;;
			"\"MAXIMIZED\"")
				# Provides $valY and $valH
				getScreenDimensions $WINDOW $(getWindowProperty $WINDOW "_MONITORS")

				margin_top=$(( $MARGIN + $(getWindowProperty $WINDOW "_OB_MARGIN_T") ))
				y_position=$(( $valY + $margin_top ))
				window_height_top=$(( ($valH/2)                                   -
				                      $(getWindowProperty $WINDOW "_OB_BORDER_T") -
				                      $(getWindowProperty $WINDOW "_OB_BORDER_B") -
				                      $margin_top                                 ))

				# If we've gotten this far without the program quitting, we can set this
				setPropertyString $WINDOW "_STATE" JUST_TOP

				# Move window
				wmctrl -r :ACTIVE: -b remove,maximized_vert                      && \
				wmctrl -r :ACTIVE: -b    add,maximized_horz                      && \
				wmctrl -r :ACTIVE: -e 0,-1,"$y_position",-1,"$window_height_top"
				;;
			*)
				exit
				;;
		esac
		;;
	-d|--down)
		case $(getWindowProperty $WINDOW "_STATE") in
			"such" | "found.")
				storeGeometry $WINDOW

				# Provides $valY and $valH
				getScreenDimensions $WINDOW $(getWindowProperty $WINDOW "_MONITORS")

				window_height_bottom=$(( ($valH/2)                                          -
				                         $(getWindowProperty $WINDOW "_OB_BORDER_T")        -
				                         $(getWindowProperty $WINDOW "_OB_BORDER_B")        -
				                         $(( $MARGIN                                     +
				                             $(getWindowProperty $WINDOW "_OB_MARGIN_B") )) ))
				y_position=$(( $valH/2 + $valY ))

				# If we've gotten this far without the program quitting, we can set this
				setPropertyString $WINDOW "_STATE" JUST_BOTTOM

				# Move window
				wmctrl -r :ACTIVE: -b remove,maximized_vert                         && \
				wmctrl -r :ACTIVE: -b    add,maximized_horz                         && \
				wmctrl -r :ACTIVE: -e 0,-1,"$y_position",-1,"$window_height_bottom"
				;;
			"\"JUST_LEFT\"" | "\"JUST_RIGHT\"")
				# Provides $valY and $valH
				getScreenDimensions $WINDOW $(getWindowProperty $WINDOW "_MONITORS")

				window_height_bottom=$(( ($valH/2)                                          -
				                         $(getWindowProperty $WINDOW "_OB_BORDER_T")        -
				                         $(getWindowProperty $WINDOW "_OB_BORDER_B")        -
				                         $(( $MARGIN                                     +
				                             $(getWindowProperty $WINDOW "_OB_MARGIN_B") )) ))
				y_position=$(( $valH/2 + $valY ))

				# Move window
				wmctrl -r :ACTIVE: -b remove,maximized_vert                         && \
				wmctrl -r :ACTIVE: -e 0,-1,"$y_position",-1,"$window_height_bottom"
				;;&
			"\"JUST_LEFT\"")
				setPropertyString $WINDOW "_STATE" BOT_LEFT
				;;&
			"\"JUST_RIGHT\"")
				setPropertyString $WINDOW "_STATE" BOT_RIGHT
				;;
			"\"TOP_LEFT\"")
				setPropertyString $WINDOW "_STATE" JUST_LEFT
				;;&
			"\"TOP_RIGHT\"")
				setPropertyString $WINDOW "_STATE" JUST_RIGHT
				;;&
			"\"TOP_LEFT\"" | "\"TOP_RIGHT\"")
				wmctrl -r :ACTIVE: -b add,maximized_vert
				;;
			"\"JUST_TOP\"")
				restoreDimensionGeometry $WINDOW
				;;
			"\"MAXIMIZED\"")
				# Provides $valY and $valH
				getScreenDimensions $WINDOW $(getWindowProperty $WINDOW "_MONITORS")

				margin_top=$(( $MARGIN + $(getWindowProperty $WINDOW "_OB_MARGIN_T") ))
				y_position=$(( $valY + $margin_top ))
				window_height_top=$(( ($valH/2)                                   -
				                      $(getWindowProperty $WINDOW "_OB_BORDER_T") -
				                      $(getWindowProperty $WINDOW "_OB_BORDER_B") -
				                      $margin_top                                 ))

				# If we've gotten this far without the program quitting, we can set this
				setPropertyString $WINDOW "_STATE" JUST_TOP

				# Move window
				wmctrl -r :ACTIVE: -b remove,maximized_vert                      && \
				wmctrl -r :ACTIVE: -b    add,maximized_horz                      && \
				wmctrl -r :ACTIVE: -e 0,-1,"$y_position",-1,"$window_height_top"
				;;
			*)
				exit
				;;
		esac
		;;
	*)
		echo "help"
		;;
esac
