#!/bin/bash

function getWindowProperty() {
	window_ID="$1"
	property_name="$2"

	echo $(xprop -id $window_ID $property_name | awk '{print $3}')
}

function setPropertyInteger() {
	window_ID="$1"
	property_name="$2"
	property_value="$3"

	xprop -id  "$window_ID"                       \
	      -f   "$property_name" 32i               \
	      -set "$property_name" "$property_value"
}
function setPropertyString() {
	window_ID="$1"
	property_name="$2"
	property_value="$3"

	xprop -id  "$window_ID"                       \
	      -f   "$property_name" 8s                \
	      -set "$property_name" "$property_value"
}

function storeGeometry() {
	window_ID="$1"




	MON=$(xrandr -q | grep -c " connected")

	case $MON in
		1 | 2 )
			setPropertyInteger $window_ID "_MONITORS" "$MON"
			;;
		3 | * )
			echo "Script cannot deal with more than 2 monitors" >&2

			exit
			;;
	esac




	eval $(xdotool getactivewindow getwindowgeometry --shell)

	# Set initial geometry and position
	setPropertyInteger $window_ID "_INITIAL_DIMENSION_X"      "$X"
	setPropertyInteger $window_ID "_INITIAL_DIMENSION_Y"      "$Y"
	setPropertyInteger $window_ID "_INITIAL_DIMENSION_WIDTH"  "$WIDTH"
	setPropertyInteger $window_ID "_INITIAL_DIMENSION_HEIGHT" "$HEIGHT"




	# WM sets window frame and border sizes
	# Titlebar height depends on fontsize of Active titlebar
	win_EXTENTS=$(xprop -id $window_ID _NET_FRAME_EXTENTS | awk ' {gsub(/,/,"");print $3,$4,$5,$6}')
	read BORDER_L BORDER_R BORDER_T BORDER_B <<< "$win_EXTENTS"

	setPropertyInteger $window_ID "_OB_BORDER_L" "$BORDER_L"
	setPropertyInteger $window_ID "_OB_BORDER_R" "$BORDER_R"
	setPropertyInteger $window_ID "_OB_BORDER_T" "$BORDER_T"
	setPropertyInteger $window_ID "_OB_BORDER_B" "$BORDER_B"
	setPropertyInteger $window_ID "_OFFSET_X"    "$(($BORDER_L + $BORDER_R))"

	# Use different corrections if window is decorated/undecorated
	if
		xprop -id $window_ID | grep -q _OB_WM_STATE_UNDECORATED
	then
		setPropertyInteger $window_ID "_OFFSET_Y" "$(($BORDER_T + $BORDER_B))"
	else
		setPropertyInteger $window_ID "_OFFSET_Y" "$(($BORDER_T * 2))"
	fi




	RC="$HOME/.config/openbox/rc.xml"

	if
		[[ -f "$RC" ]]
	then
		TAG="margins"
		RCXML=$(sed -n "/<$TAG>/,/<\/$TAG>/p" "$RC")

		setPropertyInteger $window_ID "_OB_MARGIN_L" $(grep -oPm1 "(?<=<left>)[^<]+"   <<< "$RCXML")
		setPropertyInteger $window_ID "_OB_MARGIN_R" $(grep -oPm1 "(?<=<right>)[^<]+"  <<< "$RCXML")
		setPropertyInteger $window_ID "_OB_MARGIN_T" $(grep -oPm1 "(?<=<top>)[^<]+"    <<< "$RCXML")
		setPropertyInteger $window_ID "_OB_MARGIN_B" $(grep -oPm1 "(?<=<bottom>)[^<]+" <<< "$RCXML")
	else
		echo "$RC not found" >&2

		exit 1
	fi
}

function getScreenDimensions() {   # get net workarea, if panels are present
	window_ID="$1"
	number_of_monitors="$2"



	#    X pos, Y pos, usable width, usable height
	read valX   valY   valW          valH          <<< $(echo $(xprop -root _NET_WORKAREA) | awk '{gsub(/,/,"");print $3,$4,$5,$6}')

	desktopW=$(xrandr -q | awk '/Screen/ {print $8}')  # total desktop width

	# Get monitors geometry and position ( w,h,offset_x,offset_y )
	read monA     \
	     monAgeom \
	     monB     \
	     monBgeom <<< $(echo $(xrandr -q                                                             |
	                           awk '/ connected/ {if ($3=="primary") print $1,$4; else print $1,$3}'))

	monApos=$(echo $monAgeom | awk -F "+" '{print $2}') # get offset_x
	monBpos=$(echo $monBgeom | awk -F "+" '{print $2}')
	if
		[[ $number_of_monitors != 1 ]]        # test if there are 2 monitors
	then
		if
			[[ $monApos -lt $monBpos ]]
		then
			screenW1=${monAgeom%'x'*}   # width of left screen
			screenW2=${monBgeom%'x'*}   # width of right screen
		else
			screenW2=${monAgeom%'x'*}
			screenW1=${monBgeom%'x'*}
		fi
	else
		screenW1=${monAgeom%'x'*}       # only one screen
	fi

	WINPOS=$(xwininfo -id $WINDOW | grep "Absolute upper-left X")

	if
		[[ ${WINPOS##*' '} -ge $screenW1 ]]
	then # window is on R monitor
		X_zero=$(( $desktopW - $screenW2 ))
		screenW=$(( $desktopW - $screenW1 - $(( $desktopW - $valW - $valX )) ))
	else
		X_zero=$valX                            # window is on L monitor
		screenW=$(( $screenW1 - $X_zero ))
	fi
}
####    END FUNCTIONS   ################################################



if
	[[ $2 ]]
then
	MARGIN=$2
else
	MARGIN=0
fi

WINDOW=$(xdotool getactivewindow)



case "$1" in
	-l|--left)
		case $(getWindowProperty $WINDOW "_STATE") in
			"such" | "found.")
				storeGeometry $WINDOW

				OB_border_left=$(getWindowProperty $WINDOW "_OB_BORDER_L")

				# Provides $X_zero and $screenW
				getScreenDimensions $WINDOW $(getWindowProperty $WINDOW "_MONITORS")

				if
					(( $MARGIN != 0 ))
				then
					if
						(( $MARGIN <= $OB_border_left ))
					then
						x_position=$(( $OB_border_left + $X_zero ))
					else
						x_position=$(( $MARGIN + $OB_border_left + $X_zero ))
					fi
				else
					x_position=$(( $(getWindowProperty $WINDOW "_OB_MARGIN_L") + $X_zero ))
				fi

				WIN_WIDTH_L=$(( ($screenW / 2)                           -
				                $x_position                              -
				                $(getWindowProperty $WINDOW "_OFFSET_X") +
				                $X_zero                                  ))

				# If we've gotten this far without the program quitting, we can set this
				setPropertyString $WINDOW "_STATE" JUST_LEFT

				# Move window
				wmctrl -r :ACTIVE: -b    add,maximized_vert             && \
				wmctrl -r :ACTIVE: -b remove,maximized_horz             && \
				wmctrl -r :ACTIVE: -e 0,$x_position,0,"$WIN_WIDTH_L",-1
				;;
			"JUST_RIGHT")
				exit
				;;
			"TOP_RIGHT")
				exit
				;;
			"BOT_RIGHT")
				exit
				;;
			"JUST_TOP")
				eval $(xdotool getactivewindow getwindowgeometry --shell)

				OB_border_left=$(getWindowProperty $WINDOW "_OB_BORDER_L")

				# Provides $X_zero and $screenW
				getScreenDimensions $WINDOW $(getWindowProperty $WINDOW "_MONITORS")

				if
					(( $MARGIN != 0 ))
				then
					if
						(( $MARGIN <= $OB_border_left ))
					then
						x_position=$(( $OB_border_left + $X_zero ))
					else
						x_position=$(( $MARGIN + $OB_border_left + $X_zero ))
					fi
				else
					x_position=$(( $(getWindowProperty $WINDOW "_OB_MARGIN_L") + $X_zero ))
				fi

				y_position=$(( $Y - $(getWindowProperty $WINDOW "_OFFSET_Y") ))

				WIN_WIDTH_L=$(( ($screenW / 2)                           -
				                $x_position                              -
				                $(getWindowProperty $WINDOW "_OFFSET_X") +
				                $X_zero                                  ))

				# If we've gotten this far without the program quitting, we can set this
				setPropertyString $WINDOW "_STATE" "TOP_LEFT"

				# Move window
				;;
			"JUST_BOTTOM")
				exit
				wmctrl -r :ACTIVE: -b remove,maximized_horz                                  && \
				wmctrl -r :ACTIVE: -e 0,"$x_position","$y_position","$WIN_WIDTH_L","$HEIGHT"
				;;
			"MAXIMIZED")
				exit
				;;
			*)
				exit
				;;
		esac
		;;
	-r|--right)
		case $(getWindowProperty $WINDOW "_STATE") in
			"such" | "found.")
				storeGeometry $WINDOW

				OB_border_right=$(getWindowProperty $WINDOW "_OB_BORDER_R")

				# Provides $X_zero and $screenW
				getScreenDimensions $WINDOW $(getWindowProperty $WINDOW "_MONITORS")

				if
					(( $MARGIN != 0 ))
				then
					if
						(( $MARGIN <= $OB_border_right ))
					then
						margin_right="$OB_border_right"     # don't need OB margin
					else
						margin_right=$(( $MARGIN + $OB_border_right ))
					fi
				else
					margin_right="$OB_border_right"       # add OB margin to right edge
				fi

				x_position=$(( ($screenW / 2) + $X_zero ))
				window_width=$(( ($screenW / 2)                           -
				                 $margin_right                            -
				                 $(getWindowProperty $WINDOW "_OFFSET_X") ))

				# If we've gotten this far without the program quitting, we can set this
				setPropertyString $WINDOW "_STATE" JUST_RIGHT

				# Move window
				wmctrl -r :ACTIVE: -b    add,maximized_vert                && \
				wmctrl -r :ACTIVE: -b remove,maximized_horz                && \
				wmctrl -r :ACTIVE: -e 0,"$x_position",0,"$window_width",-1
				;;
			"JUST_LEFT")
				exit
				;;
			"TOP_LEFT")
				exit
				;;
			"BOT_LEFT")
				exit
				;;
			"JUST_TOP")
				exit
				;;
			"JUST_BOTTOM")
				exit
				;;
			"MAXIMIZED")
				exit
				;;
			*)
				exit
				;;
		esac
		;;
	-u|--up)
		case $(getWindowProperty $WINDOW "_STATE") in
			"such" | "found.")
				storeGeometry $WINDOW

				# Provides $valY and $valH
				getScreenDimensions $WINDOW $(getWindowProperty $WINDOW "_MONITORS")

				margin_top=$(( $MARGIN + $(getWindowProperty $WINDOW "_OB_MARGIN_T") ))
				y_position=$(( $valY + $margin_top ))
				window_height_top=$(( ($valH/2)                                   -
				                      $(getWindowProperty $WINDOW "_OB_BORDER_T") -
				                      $(getWindowProperty $WINDOW "_OB_BORDER_B") -
				                      $margin_top                                 ))

				# If we've gotten this far without the program quitting, we can set this
				setPropertyString $WINDOW "_STATE" JUST_TOP

				# Move window
				wmctrl -r :ACTIVE: -b remove,maximized_vert                      && \
				wmctrl -r :ACTIVE: -b    add,maximized_horz                      && \
				wmctrl -r :ACTIVE: -e 0,-1,"$y_position",-1,"$window_height_top"
				;;
			"JUST_LEFT")
				exit
				;;
			"BOT_LEFT")
				exit
				;;
			"JUST_RIGHT")
				exit
				;;
			"BOT_RIGHT")
				exit
				;;
			"JUST_TOP")
				exit
				;;
			"JUST_BOTTOM")
				exit
				;;
			"MAXIMIZED")
				exit
				;;
			*)
				exit
				;;
		esac
		;;
	-d|--down)
		case $(getWindowProperty $WINDOW "_STATE") in
			"such" | "found.")
				storeGeometry $WINDOW

				# Provides $valY and $valH
				getScreenDimensions $WINDOW $(getWindowProperty $WINDOW "_MONITORS")

				window_height_bottom=$(( ($valH/2)                                          -
				                         $(getWindowProperty $WINDOW "_OB_BORDER_T")        -
				                         $(getWindowProperty $WINDOW "_OB_BORDER_B")        -
				                         $(( $MARGIN                                     +
				                             $(getWindowProperty $WINDOW "_OB_MARGIN_B") )) ))
				y_position=$(( $valH/2 + $valY ))

				# If we've gotten this far without the program quitting, we can set this
				setPropertyString $WINDOW "_STATE" JUST_BOTTOM

				# Move window
				wmctrl -r :ACTIVE: -b remove,maximized_vert                         && \
				wmctrl -r :ACTIVE: -b    add,maximized_horz                         && \
				wmctrl -r :ACTIVE: -e 0,-1,"$y_position",-1,"$window_height_bottom"
				;;
			"JUST_LEFT")
				exit
				;;
			"TOP_LEFT")
				exit
				;;
			"JUST_RIGHT")
				exit
				;;
			"TOP_RIGHT")
				exit
				;;
			"JUST_TOP")
				exit
				;;
			"MAXIMIZED")
				exit
				;;
			*)
				exit
				;;
		esac
		;;
	*)
		echo "help"
		;;
esac
